#!/usr/bin/perl
use strict;
use File::Spec;
use FindBin;
use lib map File::Spec->catdir( $FindBin::Bin, File::Spec->updir, $_ ), qw/lib extlib/;
use MT;

my $mt = MT->new();
my $convert_tools = MT->registry( 'convert_tools' );
for my $key ( keys %$convert_tools ) {
    my $tool = $convert_tools->{ $key };
    if ( $tool ) {
        my $code = MT->handler_to_coderef( $tool );
        $code->();
    }
}

1;