<?php
function get_icon( $num ) {
    $table = array(
        array('晴れ', 'sun.gif'),
        array('曇り', 'cloud.gif'),
        array('雨', 'rain.gif'),
        array('雪', 'snow.gif'),
        array('雷', 'thunder.gif'),
        array('台風', 'typhoon.gif'),
        array('霧', 'mist.gif'),
        array('小雨', 'sprinkle.gif'),
        array('牡羊座', 'aries.gif'),
        array('牡牛座', 'taurus.gif'),
        array('双子座', 'gemini.gif'),
        array('蟹座', 'cancer.gif'),
        array('獅子座', 'leo.gif'),
        array('乙女座', 'virgo.gif'),
        array('天秤座', 'libra.gif'),
        array('蠍座', 'scorpius.gif'),
        array('射手座', 'sagittarius.gif'),
        array('山羊座', 'capricornus.gif'),
        array('水瓶座', 'aquarius.gif'),
        array('魚座', 'pisces.gif'),
        array('スポーツ', 'sports.gif'),
        array('野球', 'baseball.gif'),
        array('ゴルフ', 'golf.gif'),
        array('テニス', 'tennis.gif'),
        array('サッカー', 'soccer.gif'),
        array('スキー', 'ski.gif'),
        array('バスケットボール', 'basketball.gif'),
        array('モータースポーツ', 'motorsports.gif'),
        array('ポケットベル', 'pocketbell.gif'),
        array('電車', 'train.gif'),
        array('地下鉄', 'subway.gif'),
        array('新幹線', 'bullettrain.gif'),
        array('車 (セダン)', 'car.gif'),
        array('車 (RV)', 'rvcar.gif'),
        array('バス', 'bus.gif'),
        array('船', 'ship.gif'),
        array('飛行機', 'airplane.gif'),
        array('家', 'house.gif'),
        array('ビル', 'building.gif'),
        array('郵便局', 'postoffice.gif'),
        array('病院', 'hospital.gif'),
        array('銀行', 'bank.gif'),
        array('ATM', 'atm.gif'),
        array('ホテル', 'hotel.gif'),
        array('コンビニ', '24hours.gif'),
        array('ガソリンスタンド', 'gasstation.gif'),
        array('駐車場', 'parking.gif'),
        array('信号', 'signaler.gif'),
        array('トイレ', 'toilet.gif'),
        array('レストラン', 'restaurant.gif'),
        array('喫茶店', 'cafe.gif'),
        array('バー', 'bar.gif'),
        array('ビール', 'beer.gif'),
        array('ファーストフード', 'fastfood.gif'),
        array('ブティック', 'boutique.gif'),
        array('美容院', 'parlor.gif'),
        array('カラオケ', 'karaoke.gif'),
        array('映画', 'movie.gif'),
        array('右斜め上', 'upwardright.gif'),
        array('遊園地', 'amusement.gif'),
        array('音楽', 'music.gif'),
        array('アート', 'art.gif'),
        array('演劇', 'actor.gif'),
        array('イベント', 'event.gif'),
        array('チケット', 'ticket.gif'),
        array('喫煙', 'smoking.gif'),
        array('禁煙', 'nosmoking.gif'),
        array('カメラ', 'camera.gif'),
        array('カバン', 'bag.gif'),
        array('本', 'book.gif'),
        array('リボン', 'ribbon.gif'),
        array('プレゼント', 'present.gif'),
        array('バースデー', 'birthday.gif'),
        array('電話', 'telephone.gif'),
        array('携帯電話', 'mobilephone.gif'),
        array('メモ', 'memo.gif'),
        array('TV', 'tv.gif'),
        array('ゲーム', 'game.gif'),
        array('CD', 'cd.gif'),
        array('ハート', 'heart.gif'),
        array('スペード', 'spade.gif'),
        array('ダイヤ', 'diamond.gif'),
        array('クラブ', 'club.gif'),
        array('目', 'eye.gif'),
        array('耳', 'ear.gif'),
        array('手 (グー)', 'rock.gif'),
        array('手 (チョキ)', 'scissors.gif'),
        array('手 (パー)', 'paper.gif'),
        array('右斜め下', 'downwardright.gif'),
        array('左斜め上', 'upwardleft.gif'),
        array('足', 'foot.gif'),
        array('くつ', 'shoe.gif'),
        array('眼鏡', 'glasses.gif'),
        array('車椅子', 'wheelchair.gif'),
        array('新月', 'newmoon.gif'),
        array('やや欠け月', 'moon1.gif'),
        array('半月', 'moon2.gif'),
        array('三日月', 'moon3.gif'),
        array('満月', 'fullmoon.gif'),
        array('犬', 'dog.gif'),
        array('猫', 'cat.gif'),
        array('リゾート', 'resort.gif'),
        array('クリスマス', 'xmas.gif'),
        array('左斜め下', 'downwardleft.gif'),
        array('phone to', 'phoneto.gif'),
        array('mail to', 'mailto.gif'),
        array('fax to', 'faxto.gif'),
        array('iモード', 'info01.gif'),
        array('iモード (枠付き)', 'info02.gif'),
        array('メール', 'mail.gif'),
        array('ドコモ提供', 'docomo.gif'),
        array('ドコモポイント', 'docomopoint.gif'),
        array('有料', 'yen.gif'),
        array('無料', 'free.gif'),
        array('ID', 'id.gif'),
        array('パスワード', 'key.gif'),
        array('次項有', 'enter.gif'),
        array('クリア', 'clear.gif'),
        array('サーチ (調べる)', 'search.gif'),
        array('NEW', 'new.gif'),
        array('位置情報', 'flag.gif'),
        array('フリーダイヤル', 'freedial.gif'),
        array('シャープダイヤル', 'sharp.gif'),
        array('モバQ', 'mobaq.gif'),
        array('1', 'one.gif'),
        array('2', 'two.gif'),
        array('3', 'three.gif'),
        array('4', 'four.gif'),
        array('5', 'five.gif'),
        array('6', 'six.gif'),
        array('7', 'seven.gif'),
        array('8', 'eight.gif'),
        array('9', 'nine.gif'),
        array('0', 'zero.gif'),
        array('決定', 'ok.gif'),
        array('黒ハート', 'heart01.gif'),
        array('揺れるハート', 'heart02.gif'),
        array('失恋', 'heartbreak.gif'),
        array('ハートたち (複数ハート)', 'heart04.gif'),
        array('わーい (嬉しい顔)', 'happy01.gif'),
        array('ちっ (怒った顔)', 'angry.gif'),
        array('がく～ (落胆した顔)', 'despair.gif'),
        array('もうやだ～ (悲しい顔)', 'sad.gif'),
        array('ふらふら', 'unintentionally.gif'),
        array('グッド (上向き矢印)', 'up.gif'),
        array('るんるん', 'note.gif'),
        array('いい気分 (温泉)', 'spa.gif'),
        array('かわいい', 'lovely.gif'),
        array('キスマーク', 'kissmark.gif'),
        array('ぴかぴか (新しい)', 'shine.gif'),
        array('ひらめき', 'flair.gif'),
        array('むかっ (怒り)', 'annoy.gif'),
        array('パンチ', 'punch.gif'),
        array('爆弾', 'bomb.gif'),
        array('ムード', 'notes.gif'),
        array('バッド (下向き矢印)', 'down.gif'),
        array('眠い (睡眠)', 'sleepy.gif'),
        array('exclamation', 'sign01.gif'),
        array('exclamation&question', 'sign02.gif'),
        array('exclamation×2', 'sign03.gif'),
        array('どんっ (衝撃)', 'impact.gif'),
        array('あせあせ (飛び散る汗)', 'sweat01.gif'),
        array('たらーっ (汗)', 'sweat02.gif'),
        array('ダッシュ (走り出すさま)', 'dash.gif'),
        array('ー (長音記号１)', 'sign04.gif'),
        array('ー (長音記号２)', 'sign05.gif'),
        array('カチンコ', 'slate.gif'),
        array('ふくろ', 'pouch.gif'),
        array('ペン', 'pen.gif'),
        array('人影', 'shadow.gif'),
        array('いす', 'chair.gif'),
        array('夜', 'night.gif'),
        array('soon', 'soon.gif'),
        array('on', 'on.gif'),
        array('end', 'end.gif'),
        array('時計', 'clock.gif'),
    );
    $num = ( (int) $num ) - 1;
    return $table[ $num ];
}
?>