id  : CustomObject
key : customobject
name: Custom Object Pack
version: 2.0
schema_version: 2.41
author_name: Alfasado Inc.
author_link: http://alfasado.net/
description: '<__trans phrase="Create and manage custom object.">'
l10n_class: CustomObject::L10N
config_settings:
    CustomObjectFieldScope:
        default: blog
    AllowDirectInstall:
        default: 0
    CustomObjectPerRebuild:
        default: 40
    FolderObjectPerRebuild:
        default: 5

# TODO / Workflow & Permission(create,apploval,manage)
# TODO / Search(PHP or CGI or Tag) and Shuffle, Ramdom

archive_types:
    CustomObject: ArchiveType::CustomObject
    FolderCustomObject: ArchiveType::FolderCustomObject
rebuild_options:
    CustomObject:
        code: $customobject::ArchiveType::CustomObject::rebuild_archive
    FolderCustomObject:
        code: $customobject::ArchiveType::FolderCustomObject::rebuild_archive
listing_screens:
    customobject:
        object_label: CustomObject
        primary: name
        default_sort_key: name
        condition: $customobject::CustomObject::Plugin::_customobject_permission
        view:
            - website
            - blog
            - system
    customobjectgroup:
        object_label: CustomObject Group
        primary: name
        default_sort_key: name
        condition: $customobject::CustomObject::Plugin::_group_permission
        view:
            - website
            - blog
            - system
system_filters:
    tag: $customobject::CustomObject::Listing::system_filters_tag
    customobject: $customobject::CustomObject::Listing::system_filters_customobject
    customobjectgroup: $customobject::CustomObject::Listing::system_filters_group
list_properties:
    tag: $customobject::CustomObject::Listing::list_props_tag
    customobject: $customobject::CustomObject::Listing::list_props
    customobjectgroup: $customobject::CustomObject::Listing::list_group_props
list_actions:
    customobject: $customobject::CustomObject::Listing::list_actions
    customobjectgroup: $customobject::CustomObject::Listing::list_group_actions
content_actions:
    customobject: $customobject::CustomObject::Listing::content_actions
permissions:
    blog.manage_customobject:
        label: Manage CustomObject
        group: auth_pub
        order: 1100
    blog.manage_customobjectgroup:
        label: Manage CustomObject Groups
        group: blog_admin
        order: 2200
custom_objects:
    customobject:
        id: CustomObject
        archive_types:
            - CustomObject
            - FolderCustomObject
applications:
    cms:
        methods:
            # list_customobject: $customobject::CustomObject::Plugin::_list_customobject
            # list_customobjectgroup: $customobject::CustomObject::Plugin::_list_customobject
            upload_customobject_csv: $customobject::CustomObject::Plugin::_upload_customobject_csv
            download_customobject_csv: $customobject::CustomObject::Plugin::_download_customobject_csv
            publish_customobjects: $customobject::CustomObject::Plugin::_publish_customobjects
            unpublish_customobjects: $customobject::CustomObject::Plugin::_unpublish_customobjects
            closed_customobjects: $customobject::CustomObject::Plugin::_closed_customobjects
            review_customobjects: $customobject::CustomObject::Plugin::_review_customobjects
            preview_customobject: $customobject::CustomObject::CMS::_preview_customobject
            view_customobject: $customobject::CustomObject::Plugin::_view_customobject
            view_customobjectgroup: $customobject::CustomObject::Plugin::_view_customobject
            create_customobject: $customobject::CustomObject::Plugin::_create_customobject
            add_tags_to_customobject: $customobject::CustomObject::Plugin::_add_tags_to_customobject
            remove_tags_to_customobject: $customobject::CustomObject::Plugin::_remove_tags_to_customobject
        menus:
            customobject:
                label: Custom Object
                order: 350
            customobject:list_customobject:
                label: Manage
                mode: list
                args:
                    _type: customobject
                    blog_id: 0
                order: 1
                view:
                    - website
                    - blog
                    - system
                condition: $customobject::CustomObject::Plugin::_menu_permission
            customobject:create_customobject:
                label: New
                mode: view
                args:
                    _type: customobject
                order: 2
                view:
                    - website
                    - blog
                condition: $customobject::CustomObject::Plugin::_menu_permission
            customobject:list_customobjectgroup:
                label: Manage Groups
                mode: list
                args:
                    _type: customobjectgroup
                    blog_id: 0
                order: 3
                view:
                    - website
                    - blog
                    - system
                condition: $customobject::CustomObject::Plugin::_group_menu_permission
            customobject:create_customobjectgroup:
                label: Create Group
                mode: view
                args:
                    _type: customobjectgroup
                order: 4
                view:
                    - website
                    - blog
                condition: $customobject::CustomObject::Plugin::_group_menu_permission
            customobject:edit_tags:
                label: Tags
                mode: list
                args:
                    _type: tag
                    filter_key: customobject
                order: 5
                view:
                    - website
                    - blog
                permission: edit_tags
                condition: $customobject::CustomObject::Plugin::_menu_permission
            tools:create_customobject:
                label: Create Object
                mode: create_customobject
                order: 1000
                view: system
                system_permission: administer
                condition: >
                    sub {
                        my $component = MT->component( 'CustomObject' );
                        require File::Spec;
                        my $tmpl_dir = File::Spec->catdir( $component->path, 'tmpl', 'plugin_tmpl' );
                        if ( -d $tmpl_dir ) {
                            return 1;
                        }
                        return 0;
                    }
        compose_menus:
            customobject:
                id: customobject
                label: CustomObject
                order: 1000
                mode: view
                args:
                    _type: customobject
                    class: customobject
                view:
                    - website
                    - blog
                condition: $customobject::CustomObject::Plugin::_menu_permission
object_types:
    customobject: CustomObject::CustomObject
    customobjectgroup: CustomObject::CustomObjectGroup
    customobjectorder: CustomObject::CustomObjectOrder
    template:
        customobjectgroup_id: integer
#    blog:
#        max_revisions_customobject: integer meta
    blog: $customobject::CustomObject::Object::blog_max_revisions
    fileinfo:
        customobject_id: integer
customfield_objects:
    customobject:
        context:
            - system
            - website
            - blog
        order: 10000
customfield_types: $customobject::CustomObject::Field::_customfield_types
callbacks:
    init_request: $customobject::CustomObject::Plugin::_init_request
    init_app:
        handler: $customobject::CustomObject::Field::_init_tags
        priority: 10
    MT::App::CMS::pre_run: $customobject::CustomObject::Plugin::_pre_run
    MT::App::CMS::template_param.list_common: $customobject::CustomObject::Plugin::_list_tag_param
    MT::App::CMS::template_param.edit_customobject: $customobject::CustomObject::Plugin::_edit_customobject
    MT::App::CMS::template_param.search_replace: $customobject::CustomObject::Plugin::_search_replace
    MT::App::CMS::template_output.edit_customobject: $customobject::CustomObject::Plugin::_edit_customobject_out
    MT::App::CMS::template_source.display_options: $customobject::CustomObject::Plugin::_display_options
    MT::App::CMS::template_source.template_table: $customobject::CustomObject::Plugin::_template_table
    MT::App::CMS::template_param.list_customobject: $customobject::CustomObject::Plugin::_list_customobject_param
    MT::App::CMS::template_param.list_customobjectgroup: $customobject::CustomObject::Plugin::_list_customobject_param
    MT::App::CMS::template_param.edit_customobjectgroup: $customobject::CustomObject::Plugin::_edit_customobjectgroup
    MT::App::CMS::template_param.rebuild_confirm: $customobject::CustomObject::Plugin::_rebuild_confirm
    MT::App::CMS::template_param.asset_insert: 
        handler: $customobject::CustomObject::Plugin::_asset_insert
        priority: 10
    # MT::App::CMS::template_source.cfg_plugin: $customobject::CustomObject::Plugin::_cfg_plugin
    MT::App::CMS::template_param.list_tag: $customobject::CustomObject::Plugin::_list_tag
    MT::App::CMS::template_source.list_tag: $customobject::CustomObject::Plugin::_list_tag_src
    MT::App::CMS::template_source.preview_strip: $customobject::CustomObject::CMS::_preview_strip
    MT::App::CMS::template_param.edit_template: $customobject::CustomObject::Plugin::_edit_template_param
    cms_post_save.template: $customobject::CustomObject::Plugin::_cms_post_save_template
    cms_post_delete.template: $customobject::CustomObject::Plugin::_cms_post_delete_template
    cms_post_save.customobject: CustomFields::App::CMS::CMSPostSave_customfield_objs
    cms_pre_save.customobject: $customobject::CustomObject::Plugin::_cms_pre_save_customobject
    cms_delete_permission_filter.customobject: $customobject::CustomObject::Plugin::_cms_pre_save_customobject
    # cms_post_delete.customobject: $customobject::CustomObject::Plugin::_cms_post_delete
    cms_post_delete.folder: $customobject::CustomObject::Plugin::_cms_post_delete_folder
    cms_save_filter.customobject: $customobject::CustomObject::Plugin::_cb_cmssavefilter_customfield_objs
    MT::App::CMS::template_source.footer: $customobject::CustomObject::Plugin::_footer_source
    cms_pre_save.blog: $customobject::CustomObject::Plugin::_cms_pre_save_blog
    cms_pre_save.website: $customobject::CustomObject::Plugin::_cms_pre_save_blog
    cms_pre_save.field: $customobject::CustomObject::Plugin::_cms_pre_save_field
    MT::App::CMS::template_param.view_log: $customobject::CustomObject::Plugin::_view_log
    MT::App::CMS::template_param.cfg_prefs: $customobject::CustomObject::Plugin::_cfg_prefs_param
    cms_pre_load_filtered_list.customobject: $customobject::CustomObject::Listing::_cms_pre_load_filtered_list
    cms_pre_load_filtered_list.customobjectgroup: $customobject::CustomObject::Listing::_cms_pre_load_filtered_list_group
    list_template_param.customobject: $customobject::CustomObject::Listing::_list_template_param
    list_template_param.customobjectgroup: $customobject::CustomObject::Listing::_list_template_param
    MT::Blog::post_clone: $customobject::CustomObject::Tools::clone_object
    template_param.clone_blog: $customobject::CustomObject::Tools::clone_blog
    cms_edit.template:
        handler: $customobject::CustomObject::Plugin::cms_edit_template
        priority: 1
    cms_pre_preview.template: $customobject::CustomObject::Plugin::_cms_pre_preview
    save_permission_filter.customobjectorder: sub { MT->instance->error( MT->translate( 'Invalid request.' ) ); }
    delete_permission_filter.customobjectorder: sub { MT->instance->error( MT->translate( 'Invalid request.' ) ); }
    cms_post_delete.customobject: $customobject::CustomObject::Plugin::_cms_post_delete_customobject
    restore: $customobject::CustomObject::Plugin::_cb_restore
    CustomObject::CustomObjectOrder::post_save: $customobject::CustomObject::Plugin::_cb_customobjectorder_post_save
    cms_post_delete.blog: $customobject::CustomObject::Plugin::_cb_blog_post_delete
    tasks:
        - handler: $customobject::CustomObject::Field::_init_tags
          priority: 1
    MT::App::CMS::take_down: >
        sub {
            my $app = MT->instance;
            return 1 unless $app->mode eq 'plugin_control';
            my $plugin = MT->component( 'CustomObjectConfig' );
            my $switch = MT->config( 'PluginSwitch' ) || {};
            $switch->{ $plugin->{ plugin_sig } } = 1;
            MT->config( 'PluginSwitch', $switch, 1 );
            MT->config->save_config();
        }
tasks:
    customobject_tasks:
        label: CustomObject Scheduled Task
        code: $customobject::CustomObject::Tools::_scheduled_task
        priority: 5
        frequency: 180
    customobject_adjust_order:
        label: Cleanup order
        code: $customobject::CustomObject::Tools::_task_adjust_order
        frequency: 180
upgrade_functions:
    install_role_customobject:
        plugin: CustomObject
        code: $customobject::CustomObject::Plugin::_install_role
    install_role_customobject_nv:
        plugin: CustomObject
        version_limit: 2.34
        code: $customobject::CustomObject::Plugin::_install_role
tags:
    block:
        CustomObjects: $customobject::CustomObject::Tags::_hdlr_customobjects
        CustomObject: $customobject::CustomObject::Tags::_hdlr_customobject
        CustomObjectsHeader: $customobject::CustomObject::Tags::_hdlr_pass_tokens
        CustomObjectsFooter: $customobject::CustomObject::Tags::_hdlr_pass_tokens
        CustomObjectTags: $customobject::CustomObject::Tags::_hdlr_customobject_tags
        CustomObjectAuthor: $customobject::CustomObject::Tags::_hdlr_customobject_author
        CustomObjectIfTagged?: $customobject::CustomObject::Tags::_hdlr_if_customobject_tagged
        CustomObjectColumns: $customobject::CustomObject::Tags::_hdlr_customobject_columns
        CustomObjectColumnsHeader: $customobject::CustomObject::Tags::_hdlr_pass_tokens
        CustomObjectColumnsFooter: $customobject::CustomObject::Tags::_hdlr_pass_tokens
        IfNotSent?: $customobject::CustomObject::Tags::_hdlr_if_not_sent
        IfNonSystemScope?: $customobject::CustomObject::Tags::_hdlr_if_not_system
        IfHyperion?: $customobject::CustomObject::Tags::_hdlr_if_hyperion
        SetContext: $customobject::CustomObject::Tags::_hdlr_setcontext
        CustomObjectFolder: $customobject::CustomObject::Tags::_hdlr_customobject_folder
        IfPlugin?: $customobject::CustomObject::Tags::_hdlr_if_component
    function:
        CustomObjectBlogID: $customobject::CustomObject::Tags::_hdlr_customobject_column
        CustomObjectID: $customobject::CustomObject::Tags::_hdlr_customobject_column
        CustomObjectPermalink: $customobject::CustomObject::Tags::_hdlr_customobject_permalink
        CustomObjectFolderLink: $customobject::CustomObject::Tags::_hdlr_folder_link
        CustomObjectBasename: $customobject::CustomObject::Tags::_hdlr_customobject_basename
        CustomObjectName: $customobject::CustomObject::Tags::_hdlr_customobject_column
        CustomObjectBody: $customobject::CustomObject::Tags::_hdlr_customobject_column
        CustomObjectKeywords: $customobject::CustomObject::Tags::_hdlr_customobject_column
        CustomObjectStatus: $customobject::CustomObject::Tags::_hdlr_customobject_column
        CustomObjectLabel: $customobject::CustomObject::Tags::_hdlr_customobject_label
        CustomObjectAuthorDisplayName: $customobject::CustomObject::Tags::_hdlr_author_displayname
        CustomObjectCreatedOn: $customobject::CustomObject::Tags::_hdlr_customobject_date
        CustomObjectModifiedOn: $customobject::CustomObject::Tags::_hdlr_customobject_date
        CustomObjectAuthoredOn: $customobject::CustomObject::Tags::_hdlr_customobject_date
        CustomObjectPeriodOn: $customobject::CustomObject::Tags::_hdlr_customobject_date
        CustomObjectsCount: $customobject::CustomObject::Tags::_hdlr_customobjects
        CustomObjectColumn: $customobject::CustomObject::Tags::_hdlr_customobject_column
        CustomObjectColumnName: $customobject::CustomObject::Tags::_hdlr_customobject_column_name
        CustomObjectColumnValue: $customobject::CustomObject::Tags::_hdlr_customobject_column_value
        CustomObjectFieldScope: $customobject::CustomObject::Tags::_hdlr_customobjectfieldscope
        Trans: $customobject::CustomObject::Tags::_hdlr_trans
        ComponentPath: $customobject::CustomObject::Tags::_hdlr_component_path
        CustomFieldColumnValue: $customobject::CustomObject::Tags::_hdlr_customfield_column
init: $customobject::CustomObject::Plugin::initializer
backup_instructions:
    customobject:
        order: 540
    customobjectgroup:
        order: 550
    customobjectorder:
        order: 560
